language: python
python:
  - "3.4.1"
services:
  - postgresql
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database fast_food_db;' -U postgres
script: 
  - python -m pytest && coverage run -m pytest && coverage report
after_success: 
  - coveralls 